### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ruudiluca** [Kaos1337/SimpleSpleef-Evolution#38]
2013-01-16 00:13:05 [SEVERE] Could not pass event PlayerDeathEvent to SimpleSpleef v3.4.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:332)
at net.minecraft.server.v1_4_6.EntityPlayer.die(EntityPlayer.java:255)
at net.minecraft.server.v1_4_6.EntityLiving.damageEntity(EntityLiving.java:758)
at net.minecraft.server.v1_4_6.EntityHuman.damageEntity(EntityHuman.java:615)
at net.minecraft.server.v1_4_6.EntityPlayer.damageEntity(EntityPlayer.java:308)
at net.minecraft.server.v1_4_6.Entity.burn(Entity.java:802)
at net.minecraft.server.v1_4_6.Entity.move(Entity.java:700)
at net.minecraft.server.v1_4_6.EntityLiving.e(EntityLiving.java:988)
at net.minecraft.server.v1_4_6.EntityHuman.e(EntityHuman.java:1144)
at net.minecraft.server.v1_4_6.EntityLiving.c(EntityLiving.java:1306)
at net.minecraft.server.v1_4_6.EntityHuman.c(EntityHuman.java:305)
at net.minecraft.server.v1_4_6.EntityLiving.j_(EntityLiving.java:534)
at net.minecraft.server.v1_4_6.EntityHuman.j_(EntityHuman.java:154)
at net.minecraft.server.v1_4_6.EntityPlayer.g(EntityPlayer.java:193)
at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:351)
at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.IllegalArgumentException: Material cannot be null
at org.apache.commons.lang.Validate.notNull(Validate.java:203)
at org.bukkit.craftbukkit.v1_4_6.inventory.CraftInventory.all(CraftInventory.java:171)
at net.kaoslabs.simplespleef.game.GameStandard.removeShovelItem(GameStandard.java:2044)
at net.kaoslabs.simplespleef.game.GameStandard.playerLoses(GameStandard.java:1700)
at net.kaoslabs.simplespleef.game.GameStandard.onPlayerDeath(GameStandard.java:992)
at net.kaoslabs.simplespleef.game.GameHandler.onEntityDeath(GameHandler.java:553)
at sun.reflect.GeneratedMethodAccessor257.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
... 28 more

**Comment by minecrafter** [comment]
Make sure you defined an shovel item.
