### ISSUE TITLE
Player join

### ISSUE THREAD

**Issue by kustomcraft2** [Kaos1337/SimpleSpleef-Evolution#7]
On player join this error shows...

29.08 10:09:45 [Server] INFO ... 14 more
29.08 10:09:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
29.08 10:09:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:601)
29.08 10:09:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.08 10:09:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
29.08 10:09:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.08 10:09:45 [Server] INFO at net.kaoslabs.simplespleef.game.GameHandler.onPlayerJoin(GameHandler.java:618)
29.08 10:09:45 [Server] INFO at net.kaoslabs.simplespleef.game.GameStandard.onPlayerJoin(GameStandard.java:937)
29.08 10:09:45 [Server] INFO Caused by: java.lang.NullPointerException
29.08 10:09:45 [Server] INFO at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
29.08 10:09:45 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
29.08 10:09:45 [Server] INFO at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
29.08 10:09:45 [Server] INFO at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
29.08 10:09:45 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:581)
29.08 10:09:45 [Server] INFO at net.minecraft.server.DedicatedServerConnection.b(SourceFile:29)
29.08 10:09:45 [Server] INFO at net.minecraft.server.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44)
29.08 10:09:45 [Server] INFO at net.minecraft.server.NetLoginHandler.c(NetLoginHandler.java:41)
29.08 10:09:45 [Server] INFO at net.minecraft.server.NetLoginHandler.d(NetLoginHandler.java:121)
29.08 10:09:45 [Server] INFO at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:92)
29.08 10:09:45 [Server] INFO at net.minecraft.server.ServerConfigurationManagerAbstract.c(ServerConfigurationManagerAbstract.java:161)
29.08 10:09:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
29.08 10:09:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
29.08 10:09:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
29.08 10:09:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
29.08 10:09:45 [Server] INFO org.bukkit.event.EventException
29.08 10:09:45 [Server] SEVERE Could not pass event PlayerJoinEvent to SimpleSpleef

My plugins: 29.08 10:12:04 [Server] INFO Plugins (49): Orebfuscator, bPermissions, JoinMessage, PqShout, FindLand, Websend, SpamGuard, Vault, Multiverse-Core, PlayerTimer, Rebalance Villagers, bChatManager, SkinList, EndReset, DynamicMOTD, DisguiseCraft, AntiAd, MultiCommand, BiomeBrush, KcNoFly, SkylandsPlus, Votifier, CommandBlocker, MobArena, EnjiinShopBridge, WorldEdit, NoCheatPlus, PqWelcome, Skybank, LogBlock, Paintball, WorldGuard, boosCooldowns, InfinitePlots, KcNoTp, CasinoSlots, SignEdit, PqPlots, Lockette, ScheduledAnnouncer2, SimpleSpleef, InfiniteClaims, Essentials, CreativeControl, Enjin Minecraft Plugin, Protection, ChestShop, EssentialsSpawn, V10FenceRegios

My config:
# Simple Spleef configuration
# Note on materials: If you use numbers for IDs and data values, make sure that you use an amount! E.g.: 1:35:5 or WOOL:5 works, but not 35:5!
# RED_WOOL does not work! Use WOOL:14 instead!
# Also, if you use single item ids (like 42 for iron block, make sure to suround them with ' - e.g. '42'. If you forget to do this, Bukkit
# will interpret the value as integer and bug SimpleSpleef...
# Material ids/names can be found at https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Material.java
# Version number of configuration - do not touch! It is used for automatic updates of configuration settings.

version: 3
language: en
settings:
  updateNotificationOnStart: true
  updateNotificationOnLogin: true
  defaultArena: default
  enableSigns: true
  useSignPermissions: true
  signsFirstLine: '[Spleef]'
  signsOnlyRightClick: false
  announceGame: false
  announceJoin: true
  announceTeam: false
  announceReady: false
  announceStart: false
  announceStop: false
  announceDelete: false
  announceCountdown: false
  announceLose: false
  announceWin: false
  announcePrize: false
  announcementRadius: -1
  sendMessagesToConsole: true
  preventTeleportingDuringGames: true
  keepOriginalLocationsSeconds: 3600
  changeGameModeBackToCreative: true
  enableStatistics: true
  statisticsModule: file
  statisticsSettings: false
arenas:
  default:
    name: Spleef
    type: standard
    enabled: true
    minimumPlayers: 2
    maximumPlayers: 0
    remainingPlayersWin: 1
    announceOnJoin: true
    spleeferStart: true
    teamCommand: false
    teamBlockMaterialBlue: WOOL:11
    teamBlockMaterialRed: WOOL:14
    teamJoiningAlsoReadies: true
    useReady: false
    readyAutoStart: true
    readyBlockMaterial: '42'
    readyTimeout: 0
    emptyInventoryToJoin: false
    emptyInventoryToSpectate: false
    clearInventory: true
    addToInventory: false
    addInventoryItems:
    entryFee: 1.0
    entryFeeGoesToPlayer: Zorox111
    entryFeeAmountToPlayer: 5.0
    giveItemPrizes: true
    itemPrizes:
    - 1:APPLE
    - 1:BED
    - 6:BOOK
    - 1:CAKE
    - 1:CHAINMAIL_HELMET
    - 16:CLAY_BALL
    - 1:COMPASS
    - 4:COOKED_FISH
    - 1:DIAMOND
    - 1:FLINT_AND_STEEL
    - 1:GOLD_INGOT
    - 4:IRON_INGOT
    - 1:GLOWSTONE
    - 1:GOLD_HELMET
    - 16:INK_SACK
    - 1:IRON_HELMET
    - 2:OBSIDIAN
    - 6:RED_ROSE
    - 3:SNOW_BLOCK
    - 6:STRING
    - 3:SULPHUR
    - 1:TNT
    - 6:YELLOW_FLOWER
    - 1:MELON_SEEDS
    - 1:EYE_OF_ENDER
    - 1:GRASS
    - 4:SMOOTH_BRICK:1
    prizeMoneyPerPlayer: 5.0
    prizeMoneyFixed: 0.0
    prizeExperiencePerPlayer: 0
    prizeExperienceFixed: 0
    refundMoney: 0.0
    loseOnTouchBlocks: false
    loseBlocks:
    - STATIONARY_WATER
    - STATIONARY_LAVA
    winOnTouchBlocks: false
    winBlocks:
    - GOLD_BLOCK
    loseOnDeath: true
    loseOnLogout: true
    noHunger: true
    noPvP: true
    blockDegeneration: -1
    degeneratingBlocks:
    - SNOW_BLOCK
    allowDigBlocks:
    - SNOW_BLOCK
    disallowDigBlocks:
    - STONE
    instantDig: false
    playersReceiveShovelAtGameStart: true
    playersLoseShovelAtGameEnd: true
    shovelItem: IRON_SPADE
    countdownFrom: 10
    allowBlockPlacing: false
    blockDropping: true
    diggingIfArenaUndefined: floorOnly
    diggingIfFloorUndefined: inArena
    protectArena: true
    disallowCreatureSpawns: true
    enableExplosionsDuringGame: false
    restoreArenaAfterGame: true
    simpleRestorerBlock: SNOW_BLOCK
    restoreArenaAfterGameTimer: 0
    enableBackCommand: false
    arenaFloorDissolvesAfter: 30
    arenaFloorDissolveTick: 5
    arenaFloorRepairsAfter: -1
    arenaFloorRepairTick: 10
    arenaTimeout: 0
    arena:
      enabled: false
      a:
        world: world
        x: 0
        y: 0
        z: 0
      b:
        world: world
        x: 0
        y: 0
        z: 0
    floor:
      enabled: false
      a:
        world: world
        x: 0
        y: 0
        z: 0
      b:
        world: world
        x: 0
        y: 0
        z: 0
    lose:
      enabled: false
      a:
        world: world
        x: 0
        y: 0
        z: 0
      b:
        world: world
        x: 0
        y: 0
        z: 0
    win:
      enabled: false
      a:
        world: world
        x: 0
        y: 0
        z: 0
      b:
        world: world
        x: 0
        y: 0
        z: 0
    loungeSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    gameSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    redSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    blueSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    spectatorSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    loseSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    winnerSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
checkCommands:
  activateWhitelist: true
  whitelist:
- ^/spl
- ^/spla

**Comment by Kaos1337** [comment]
Hi,
can you try if happen with this dev version too? http://www.mediafire.com/?h5xrrx1l91x3al5
Regards.
